---
- hosts: all
  become: yes
  roles:
    - common

- hosts: all
  become_user: "{{username}}"
  vars_files:
    - vars/main.yml
  roles:
    - nigel

- hosts: development
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  vars_files:
    - vars/main.yml
  roles:
    - zzet.rbenv

- hosts: development
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - postgresql
    - { role: geerlingguy.mysql }
