- name: write .bash_profile
  template: src=bash_profile.j2 dest=/home/nigelks/.bash_profile
- name: set git config
  shell: git config --global user.email {{git.email}}
  shell: git config --global user.name {{git.name}}
- name: get dotfiles
  git: repo=https://github.com/soon0009/dotfiles.git dest=~/.dotfiles update=yes
- name: install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
- name: install dotfiles
  shell: cd ~/.dotfiles && ./install.sh
